config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :projects


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  status     :integer
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :task_groups, dependent: :destroy

  enum status: {
    active: 0,
    inactive: 1
  }

  def destroy
    inactive!
  end
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id            :integer          not null, primary key
#  description   :text
#  status        :integer          default("pending"), not null
#  title         :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  project_id    :integer          not null
#  task_group_id :integer          not null
#
# Indexes
#
#  index_tasks_on_project_id     (project_id)
#  index_tasks_on_task_group_id  (task_group_id)
#
# Foreign Keys
#
#  project_id     (project_id => projects.id)
#  task_group_id  (task_group_id => task_groups.id)
#
class Task < ApplicationRecord
  belongs_to :task_group
  belongs_to :project

  enum status: {
    pending: 0,
    completed: 1,
    archived: 2
  }

  def destroy
    archived!
  end
end

app/models/task_group.rb
# == Schema Information
#
# Table name: task_groups
#
#  id         :integer          not null, primary key
#  position   :integer
#  status     :integer          default("active"), not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  project_id :integer          not null
#
# Indexes
#
#  index_task_groups_on_project_id  (project_id)
#
# Foreign Keys
#
#  project_id  (project_id => projects.id)
#
class TaskGroup < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :project

  enum status: {
    active: 0,
    inactive: 1
  }

  def destroy
    inactive!
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string           not null
#  gender                 :integer          not null
#  last_name              :string           not null
#  phone                  :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  social_media           :json
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  enum gender: {
    female: 0,
    male: 1
  }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
  before_action :authenticate_user!
  layout "admin"
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /admin/users or /admin/users.json
  def index
    @users = User.all
  end

  # GET /admin/users/1 or /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users or /admin/users.json
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /admin/users/1 or /admin/users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        redirect_to admin_user_url(@user), notice: "User was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  # DELETE /admin/users/1 or /admin/users/1.json
  def destroy
    @user.destroy!

    redirect_to admin_users_url, notice: "User was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :phone, :gender, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :destroy, :update]

  def index
    @projects = Project.active
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    if @project.save
      redirect_to projects_path, notice: 'Project was successfully created'
    else
      render :new, alert: 'Project could not be created'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path(@project), notice: 'Project was successfully updated'
    else
      render :edit, notice: 'Project could not be updated'
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_path, notice: "Project destroyed successfully"
    else
      redirect_to projects_path, alert: "Project not destroyed successfully"
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :status)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_form.html.slim
= simple_form_for [:admin, @user] do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :email
    = f.input :first_name
    = f.input :last_name
    = f.input :phone
    = f.input :gender, collection: User.genders
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit

app/views/admin/users/_user.html.slim
div id="#{dom_id user}"
  p
    strong Email:
    =< user.email

app/views/admin/users/edit.html.slim
h1 Editing user

== render "form", user: @user

br

div
  => link_to "Show this user", [:admin, @user]
  '|
  =< link_to "Back to users", admin_users_path

app/views/admin/users/index.html.slim
.admin-hero
  .hero-content.flex.justify-between.bg-white.mb-6.p-6.rounded-md.border-spacing-1 
    .admin-hero-title.font-bold.text-3xl[class="text-[#7a7a7a]"]
      span.text-2xl.md:text-3xl Users
    .admin-hero-actions.button 
      span = link_to "New user", new_admin_user_path, :class => 'button'

.admin-section
    .card.bg-white.border-spacing-1.rounded-md.border-spacing-1 
      .card-header.flex.items-center.gap-4.py-4.px-6[class="border-b-[1px]"] 
        span.icon.inline-flex.items-center
          = raw File.read('app/assets/images/users.svg')
        span.header-title.font-bold.pt-1 Users
      .card-content.py-4.px-6 
        .table-content   
          - @users.each do |user|
            .field.flex
              span == render user
              span &nbsp;
              p = link_to "Show this user", [:admin, user]
      .card-footer.py-4.px-6[class="border-t-[1px]"]  
        .footer-content.flex.justify-between 
          .lef
          .right
            span Pagination

app/views/admin/users/new.html.slim
h1 New user

== render "form", user: @user

br

div
  = link_to "Back to users", admin_users_path

app/views/admin/users/show.html.slim
p style="color: green" = notice

== render @user

div
  => link_to "Edit this user", edit_admin_user_path(@user)
  '|
  =< link_to "Back to users", admin_users_path

  = button_to "Destroy this user", [:admin, @user], method: :delete

app/views/layouts/_menu.html.slim
nav
    ul
        - if user_signed_in?
            li = link_to "Logout", destroy_user_session_path, "data-turbo-method": :delete 

app/views/layouts/admin.html.slim
doctype html
html
  head
    title
      | Admin RailsTask
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body.bg-gray-200.font-body
    .admin-layout.flex.w-
      = render "layouts/admin/aside"
    
      .layout-admin-container.h-screen.flex.flex-col.flex-1.[class="md:[calc(100vw - 15rem)] pl-[3.5rem] md:pl-[15rem]"]
          = render "layouts/admin/header"
          .admin-layout-body.flex-1.overflow-auto.p-6.mb-6
            = yield
          = render "layouts/admin/footer"
            

app/views/layouts/admin/_aside.html.slim
aside.layout-admin-aside.fixed.z-50.top-0.bottom-0.left-0.bg-black.text-white[class="transition[width] ease-in-out w-[3.5rem] md:w-60"]
    .admin-aside-brand.h-16.border-white.bg-slate-950
        .aside-brand-field.h-full.flex.items-center.px-4.md:px-8
            span.icon 
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="25px" width="25px" xmlns="http://www.w3.org/2000/svg"><path d="M332.8 320h38.4c6.4 0 12.8-6.4 12.8-12.8V172.8c0-6.4-6.4-12.8-12.8-12.8h-38.4c-6.4 0-12.8 6.4-12.8 12.8v134.4c0 6.4 6.4 12.8 12.8 12.8zm96 0h38.4c6.4 0 12.8-6.4 12.8-12.8V76.8c0-6.4-6.4-12.8-12.8-12.8h-38.4c-6.4 0-12.8 6.4-12.8 12.8v230.4c0 6.4 6.4 12.8 12.8 12.8zm-288 0h38.4c6.4 0 12.8-6.4 12.8-12.8v-70.4c0-6.4-6.4-12.8-12.8-12.8h-38.4c-6.4 0-12.8 6.4-12.8 12.8v70.4c0 6.4 6.4 12.8 12.8 12.8zm96 0h38.4c6.4 0 12.8-6.4 12.8-12.8V108.8c0-6.4-6.4-12.8-12.8-12.8h-38.4c-6.4 0-12.8 6.4-12.8 12.8v198.4c0 6.4 6.4 12.8 12.8 12.8zM496 384H64V80c0-8.84-7.16-16-16-16H16C7.16 64 0 71.16 0 80v336c0 17.67 14.33 32 32 32h464c8.84 0 16-7.16 16-16v-32c0-8.84-7.16-16-16-16z"></path></svg>
            span.label.hidden.md:block.font-sans.text-xl.font-semibold &nbsp;KabanUp
        
    .admin-aside-menu.h-full.bg-slate-800
        = render "layouts/admin/menu"
    .admin-aside-botton
        .aside-bottom-field Bottom

app/views/layouts/admin/_footer.html.slim
footer.admin-footer 
    .footer.content.flex.justify-between.bg-white.p-4.border-spacing-1 
        .lef
        .right
            .footer-copyright
                span
                    b &copy; 2024, Farias Brito.
                    b &nbsp; KabanUp

app/views/layouts/admin/_header.html.slim
header.admin-header.min-h-16.bg-white.shadow-sm.z-10
    .admin-header-navbar.h-full
        .navbar-container.mx-auto.flex.h-full.justify-around.text-slate-800[class="w-5/6"]
            .navbar-start.w-full.flex.items-center
            
            .navbar-end.w-full.flex.items-center.justify-end
                .navbar-menu.hidden.md:block.relative.group.py-4.px-6.hover:bg-gray-200.[class="border-x-[1px]"] 
                    .navbar-header
                        button.flex.justify-center.items-center.gap-4#dropdown-button 
                            span.icon
                                    = raw File.read('app/assets/images/menu.svg')
                            span.label Menu
                    .navbar-dropdown.hidden.absolute.group-hover:block.right-0.z-10.w-56.origin-top-right.rounded-md.bg-white.shadow-lg.ring-1.ring-black.ring-opacity-5.focus:outline-none.py-3
                        .navbar-item
                            .navbar-field.flex.cursor-pointer.py-2.text-base.hover:bg-gray-200
                                span.icon.px-4.inline-flex.justify-center.items-center 
                                    = raw File.read('app/assets/images/users.svg')
                                span.label.grow.pr-12 = link_to "Users", admin_users_path 
                        .navbar-item
                            .navbar-field.flex.cursor-pointer.py-2.text-base.hover:bg-gray-200
                                span.icon.px-4.inline-flex.justify-center.items-center 
                                    = raw File.read('app/assets/images/projects.svg')
                                span.label.grow.pr-12 Projects
                .navbar-user
                    .navbar-item.flex.gap-4.justify-center.items-center.py-4.px-6.hover:bg-gray-200.[class="border-r-[1px]"] 
                        img.img.inline-block.h-7.w-7.rounded-full.ring-2.ring-white src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                        span.label User
                .narvar-log-out
                    .navbar-item.relative.flex.gap-4.justify-center.items-center.hover:bg-gray-200.h-full[class="border-r-[1px]"]
                        - if user_signed_in?
                        span.icon.py-5.pl-6   
                            = raw File.read('app/assets/images/log_out.svg') 
                        span.label.py-5.pl-12.pr-8 = link_to "Logout", destroy_user_session_path, :class => 'absolute left-0 right-0 top-0 bottom-0 flex items-center justify-end py-4 pr-8', "data-turbo-method": :delete

                        

                         



        
    

app/views/layouts/admin/_menu.html.slim
.menu-label.py-4.flex.items-center.bg-slate-900.hover:bg-slate-700.text-slate-400.hover:text-slate-50.active:text-slate-50
    span.icon.px-4.inline-flex.justify-center.items-center.h-8
        = raw File.read('app/assets/images/dashboard.svg')
    span.text-lg.hidden.md:block.font-bold = link_to "Dasboard", root_path
ul.aside-menu-list.py-3
    li.aside-menu-item
        .aside-menu-field.flex.items-center.cursor-pointer.text-gray-500.hover:bg-slate-700.hover:text-slate-50.active:text-slate-50.py-2
            span.icon.px-4.inline-flex.items-center.h-8
                = raw File.read('app/assets/images/users.svg')
            span.label.hidden.md:block.pr-12.pt-1 = link_to "Users", admin_users_path
    li.aside-menu-item
        .aside-menu-field.flex.items-center.cursor-pointer.text-gray-500.hover:bg-slate-700.hover:text-slate-50.active:text-slate-50.py-2
            span.icon.px-4.inline-flex.justify-center.items-center.h-8
                = raw File.read('app/assets/images/projects.svg')
            span.label.hidden.md:block.pr-12.pt-1 Projects

            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/menu" %>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.slim
= simple_form_for @project do |f|
    .inputs 
        = f.input :title, placeholder: "Project Title"
        = f.input :status, collection: Project.statuses, include_blank: false
    .actions
        = f.submit

app/views/projects/edit.html.slim
h1 Edit

= render "form"

= link_to "Back", projects_path(@project)

app/views/projects/index.html.slim
h1 Projects 
Table 
    thead
        tr 
            th title 
            th status 
            th created_up 
            th updated_up 
    tbody
        - @projects.each do |project|
            tr 
                td = link_to project.title, project_path(project)
                td = project.status 
                td = project.created_at
                td = project.updated_at
                td
                    = link_to "Edit", edit_project_path(project) 
                    '
                    = link_to "Destroy", project_path(project), 'data-turbo-method': :delete, 'data-turbo-confirm': "Are you sure?"
= link_to "New", new_project_path

app/views/projects/new.html.slim
h1 New

= render "form"

= link_to "Back", projects_path

app/views/projects/show.html.slim
h1 = @project.title

= link_to "Back", projects_path
'
' |
= link_to "Edit", edit_project_path(@project)
'
' |
= link_to "Destroy", project_path(@project), 'data-turbo-method': :delete, 'data-turbo-confirm': "Are you sure?"